### ISSUE TITLE
run error   :No module named 'encrypt_code'

### ISSUE THREAD

**Issue by hansion731** [Technowlogy-Pushpender/technowhorse#1]
Traceback (most recent call last):
  File "paygen.py", line 2, in <module>
    import encrypt_code
ModuleNotFoundError: No module named 'encrypt_code'

**Comment by hansion731** [comment]
i get the encrypt_code.py in release pack

**Comment by PushpenderIndia** [comment]
I just forget to add it in current github repo.

but now available on both Github as well as release
