### ISSUE TITLE
ERROR : KILLED 

### ISSUE THREAD

**Issue by pretech86** [Technowlogy-Pushpender/technowhorse#2]
[*] Deleting Junk Files...
[+] Junk Files Removed Successfully!

[!] Failed To Generate Your Payload :(, Please Try Again!

i used this command on linux 

python3 paygen.py --ip 192.168.1.154 -t 10 --port 8080 -e mymail@gmail.com -p ( my password ) -l -o update

**Comment by PushpenderIndia** [comment]
Show me the error which is displayed before "Deleting Junk Files" message
