### ISSUE TITLE
No module named 'mss'

### ISSUE THREAD

**Issue by jamesmonroe2030** [Technowlogy-Pushpender/technowhorse#5]
Hello,

I m getting the below error. Using Kali Linux.

=================================================

Output Evil File Name: data
   Becoming Persistence After: 10 seconds
   Icon Path: icon/xlsx.ico

[ * * * * * * * * * * * * * * * * * * * * * * * * * ]

[?] These info above are correct? (y/n) : y

[*] Checking Dependencies...
[!] **Error : No module named 'mss'**
[*] Installing All Dependencies From Scratch...

[ * * * * * * * * * * * * * * * * * * * * * * * * * ]

[!] Unable to Install Dependencies, Please Try Again :(

**Comment by PushpenderIndia** [comment]
Please Install technowhorse using installer_linux.sh

And try again, or try to install it manually using this command:
`pip3 install mss`


also install mss module for windows version of python installed in wine using this command:
```
~/.wine/drive_c/Python37-32/python.exe -m pip install pyinstaller mss==4.0.3
```

If pip3 is not installed then it can be easily installed using this command : `apt-get install python3-pip`
